name: Release

on:
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

# Needed for semantic-release to create GitHub releases and publish to npm via OIDC
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

concurrency:
  group: semantic-release-main
  cancel-in-progress: false

jobs:
  release:
    name: Semantic Release
    # Ensure releases run only when code reaches main via GitHub Merge Queue, or when manually dispatched
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: '.nvmrc'
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run unit tests
        run: npm run test:ci
      - name: Semantic Release
        if: ${{ github.event_name == 'push' }}
        uses: cycjimmy/semantic-release-action@9cc899c47e6841430bbaedb43de1560a568dfd16 # v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
